"use client";

import { useMemo, useState } from "react";
import { ArrowRight, Info, Lock, Table2 } from "lucide-react";
import {
  FAMILY_META,
  INTERVENTION_META,
  simulateCohort,
  type CohortReport,
  type InterventionKind,
  type StateFamily,
} from "@attune/engine";
import { Button, cn, Eyebrow, familyColor, percent, SimulatedTag } from "./ui";

/**
 * Mentor / educator view. Three questions: What is happening? Why might it be happening?
 * What can I do? Aggregates only; no individual timelines, moods or answers.
 *
 * Every number here is produced by running the real Attune engine against a simulated class
 * of fictional learners (seeded, reproducible), and the page says so.
 */

const FAMILIES: StateFamily[] = ["engaged", "understimulated", "overloaded", "depleted", "social"];
const COHORT = { learners: 32, days: 5, seed: 11 };

export function EducatorView() {
  const report = useMemo(() => simulateCohort(COHORT), []);
  const first = report.daily[0]!;
  const last = report.daily[report.daily.length - 1]!;
  const hardest = [...report.concepts]
    .filter((c) => c.answers >= 10)
    .sort((a, b) => b.missRate - a.missRate);
  const actions = buildActions(report);

  return (
    <div className="mx-auto max-w-6xl px-4 pb-28 pt-8 sm:px-6">
      <div className="flex flex-wrap items-end gap-3">
        <div>
          <Eyebrow>Mentor view · Class 11-B · Exponents &amp; logarithms</Eyebrow>
          <h1 className="voice mt-2 text-[36px] leading-tight text-ink sm:text-[42px]">
            How the class is engaging this week
          </h1>
        </div>
      </div>
      <div className="mt-4 flex items-start gap-3 rounded-2xl border border-dashed border-line-strong bg-surface p-4 text-[13.5px] text-ink-2">
        <Info className="mt-0.5 size-4 shrink-0 text-muted" aria-hidden />
        <p>
          <SimulatedTag>Simulated class</SimulatedTag> {report.learners} fictional learners over{" "}
          {report.days} days ({report.decisions.toLocaleString()} adaptive decisions), generated by
          running the actual Attune engine against simulated learners (seed {report.seed}). No real
          student data. The numbers show what this view would measure, not evidence of real-world
          impact.
        </p>
      </div>

      {/* What is happening */}
      <SectionTitle n={1} title="What is happening" />
      <div className="grid gap-3 sm:grid-cols-4">
        <Stat
          label="Recovery from disengagement"
          value={percent(last.recoveryRate)}
          note={`Day ${last.day} · day 1 was ${percent(first.recoveryRate)}`}
        />
        <Stat
          label="Average engagement index"
          value={String(last.avgIndex)}
          note={`Day 1 was ${first.avgIndex}`}
        />
        <Stat
          label="May need support"
          value={String(report.needsSupport.total)}
          note="Learners, last two sessions"
        />
        <Stat
          label="Engaged share of moments"
          value={percent(last.families.engaged)}
          note={`Day 1 was ${percent(first.families.engaged)}`}
        />
      </div>
      <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1.4fr)_minmax(0,1fr)]">
        <Panel
          title="Where attention went, by day"
          subtitle="Share of decisions starting in each state family"
        >
          <FamilyColumns report={report} />
        </Panel>
        <Panel
          title="Recovery from disengagement, by day"
          subtitle="Disengaged moments that came back after an intervention"
        >
          <RecoveryLine report={report} />
        </Panel>
      </div>

      {/* Why */}
      <SectionTitle n={2} title="Why it might be happening" />
      <div className="grid gap-4 lg:grid-cols-2">
        <Panel
          title="Common reasons for disengaging"
          subtitle="How sessions started, when they didn't start engaged"
        >
          <HBars
            rows={report.disengagementPatterns
              .slice(0, 6)
              .map((p) => ({ label: p.label, value: p.share, note: percent(p.share) }))}
          />
        </Panel>
        <Panel title="Topics causing difficulty" subtitle="Share of answers missed, per concept">
          <HBars
            rows={report.concepts.map((c) => ({
              label: c.label,
              value: c.missRate,
              note: `${percent(c.missRate)} of ${c.answers}`,
            }))}
          />
          {hardest[0] && (
            <p className="mt-3 text-[13.5px] text-ink-2">
              <strong className="text-ink">{hardest[0].label}</strong> is the steepest step:{" "}
              {percent(hardest[0].missRate)} of answers missed. It builds on{" "}
              {hardest[1]?.label.toLowerCase() ?? "earlier concepts"}, which is where gaps compound.
            </p>
          )}
        </Panel>
      </div>

      {/* What to do */}
      <SectionTitle n={3} title="What you can do" />
      <div className="grid gap-3 md:grid-cols-2">
        {actions.map((a) => (
          <div key={a.title} className="rounded-2xl border border-line bg-surface p-5">
            <p className="text-[15.5px] font-medium text-ink">{a.title}</p>
            <p className="mt-1 text-[13.5px] text-ink-2">{a.because}</p>
            <p className="mt-3 inline-flex items-center gap-1.5 text-[13px] font-medium text-accent">
              <ArrowRight className="size-3.5" aria-hidden /> {a.action}
            </p>
          </div>
        ))}
      </div>

      <SectionTitle n={4} title="Which interventions work, for which moments" />
      <Panel
        title="Recovery rate by intervention and state family"
        subtitle="Cells with fewer than 3 cases are left blank rather than guessed"
      >
        <EffectivenessGrid report={report} />
      </Panel>

      <div className="mt-8 flex items-start gap-3 rounded-2xl bg-surface-2 p-5 text-[13.5px] text-ink-2">
        <Lock className="mt-0.5 size-4 shrink-0 text-muted" aria-hidden />
        <div>
          <p className="font-medium text-ink">What you can&apos;t see here, by design</p>
          <p className="mt-1">
            Individual timelines, moods, answers and reflections stay on each learner&apos;s device.
            Names appear only for learners who chose to share a summary:{" "}
            {report.needsSupport.sharedNames.length > 0 ? (
              <strong className="text-ink">{report.needsSupport.sharedNames.join(", ")}</strong>
            ) : (
              "none this week"
            )}{" "}
            ({report.needsSupport.sharedNames.length} of {report.needsSupport.total} flagged). The
            others see a gentle prompt to reach out instead.
          </p>
        </div>
      </div>
    </div>
  );
}

function buildActions(report: CohortReport) {
  const out: { title: string; because: string; action: string }[] = [];
  const hardest = [...report.concepts]
    .filter((c) => c.answers >= 10)
    .sort((a, b) => b.missRate - a.missRate)[0];
  if (hardest) {
    out.push({
      title: `Teach ${hardest.label.toLowerCase()} with a worked example first`,
      because: `${percent(hardest.missRate)} of answers on it were missed across the class.`,
      action: "10 minutes of worked examples before the next assignment",
    });
  }
  const best = (family: StateFamily) =>
    report.effectiveness
      .filter((e) => e.family === family && e.tries >= 5)
      .sort((a, b) => b.recoveries / b.tries - a.recoveries / a.tries)[0];
  const overloaded = best("overloaded");
  if (overloaded) {
    out.push({
      title: `When students are overloaded, try ${INTERVENTION_META[overloaded.kind].label.toLowerCase()} before re-teaching`,
      because: `It brought back ${percent(overloaded.recoveries / overloaded.tries)} of overloaded moments (${overloaded.recoveries} of ${overloaded.tries}).`,
      action: "Break the next hard problem into three checked steps",
    });
  }
  const bored = best("understimulated");
  if (bored) {
    out.push({
      title: `Under-stimulated students respond to ${INTERVENTION_META[bored.kind].label.toLowerCase()}`,
      because: `${percent(bored.recoveries / bored.tries)} recovery (${bored.recoveries} of ${bored.tries}). Repetition is the usual culprit.`,
      action: "Offer an optional stretch problem alongside the worksheet",
    });
  }
  const social = best("social");
  out.push({
    title: `${report.needsSupport.total} learners may need a human check-in`,
    because:
      report.needsSupport.reasons.map((r) => `${r.label}: ${r.count}`).join(" · ") ||
      "Flagged from the last two sessions.",
    action: social
      ? `Pair isolated learners into missions (${percent(social.recoveries / social.tries)} recovery when disconnected)`
      : "A short, low-stakes check-in, not an intervention",
  });
  return out;
}

/* ------------------------------------------------------------------------------------------ */

function SectionTitle({ n, title }: { n: number; title: string }) {
  return (
    <h2 className="mb-3 mt-10 flex items-center gap-2 text-[17px] font-medium text-ink">
      <span className="flex size-6 items-center justify-center rounded-full bg-ink font-mono text-[12px] text-inverse">
        {n}
      </span>
      {title}
    </h2>
  );
}

function Stat({ label, value, note }: { label: string; value: string; note: string }) {
  return (
    <div className="rounded-2xl border border-line bg-surface p-4">
      <p className="text-[12.5px] text-muted">{label}</p>
      <p className="mt-1 text-[30px] font-medium leading-tight text-ink">{value}</p>
      <p className="mt-1 text-[12.5px] text-ink-2">{note}</p>
    </div>
  );
}

function Panel({
  title,
  subtitle,
  children,
}: {
  title: string;
  subtitle: string;
  children: React.ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-line bg-surface p-5">
      <p className="text-[14.5px] font-medium text-ink">{title}</p>
      <p className="text-[12.5px] text-muted">{subtitle}</p>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function FamilyColumns({ report }: { report: CohortReport }) {
  const [table, setTable] = useState(false);
  const [hover, setHover] = useState<{ day: number; family: StateFamily } | null>(null);
  const h = 200;
  const w = 460;
  const pad = { l: 34, r: 8, t: 8, b: 24 };
  const band = (w - pad.l - pad.r) / report.daily.length;
  const barW = Math.min(36, band * 0.6);
  const y = (v: number) => pad.t + (1 - v) * (h - pad.t - pad.b);

  return (
    <div>
      <div className="mb-2 flex flex-wrap items-center justify-between gap-2">
        <div className="flex flex-wrap gap-x-4 gap-y-1 text-[12px] text-ink-2">
          {FAMILIES.map((f) => (
            <span key={f} className="inline-flex items-center gap-1.5">
              <span
                className="inline-block size-2.5 rounded-sm"
                style={{ background: familyColor(f) }}
                aria-hidden
              />
              {FAMILY_META[f].label}
            </span>
          ))}
        </div>
        <Button size="sm" variant="ghost" onClick={() => setTable((t) => !t)} aria-pressed={table}>
          <Table2 className="size-3.5" /> {table ? "Chart" : "Table"}
        </Button>
      </div>
      {table ? (
        <table className="w-full text-[12.5px]">
          <thead>
            <tr className="text-left text-muted">
              <th className="py-1 font-normal">Day</th>
              {FAMILIES.map((f) => (
                <th key={f} className="py-1 text-right font-normal">
                  {FAMILY_META[f].label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="tabular">
            {report.daily.map((d) => (
              <tr key={d.day} className="border-t border-line">
                <td className="py-1">{d.day}</td>
                {FAMILIES.map((f) => (
                  <td key={f} className="py-1 text-right">
                    {percent(d.families[f])}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <div className="relative">
          <svg
            viewBox={`0 0 ${w} ${h}`}
            className="w-full"
            role="img"
            aria-label="Stacked columns of state-family share per day"
            onMouseLeave={() => setHover(null)}
          >
            {[0, 0.5, 1].map((v) => (
              <g key={v}>
                <line x1={pad.l} x2={w - pad.r} y1={y(v)} y2={y(v)} stroke="var(--chart-grid)" />
                <text
                  x={pad.l - 6}
                  y={y(v) + 4}
                  textAnchor="end"
                  fontSize={10.5}
                  fill="var(--muted)"
                >
                  {v * 100}%
                </text>
              </g>
            ))}
            {report.daily.map((d, i) => {
              const cx = pad.l + band * i + band / 2;
              let acc = 0;
              return (
                <g key={d.day}>
                  {FAMILIES.map((f) => {
                    const v = d.families[f];
                    const top = y(acc + v);
                    const bottom = y(acc);
                    acc += v;
                    if (v <= 0) return null;
                    return (
                      <rect
                        key={f}
                        x={cx - barW / 2}
                        y={top + 1}
                        width={barW}
                        height={Math.max(0, bottom - top - 2)}
                        rx={2}
                        fill={familyColor(f)}
                        opacity={hover && (hover.day !== d.day || hover.family !== f) ? 0.5 : 1}
                        onMouseEnter={() => setHover({ day: d.day, family: f })}
                      />
                    );
                  })}
                  <text x={cx} y={h - 6} textAnchor="middle" fontSize={11} fill="var(--muted)">
                    Day {d.day}
                  </text>
                </g>
              );
            })}
          </svg>
          {hover && (
            <p className="mt-1 text-[12.5px] text-ink-2" aria-live="polite">
              Day {hover.day}:{" "}
              <strong className="text-ink">
                {percent(report.daily[hover.day - 1]!.families[hover.family])}
              </strong>{" "}
              of decisions started {FAMILY_META[hover.family].label.toLowerCase()}.
            </p>
          )}
        </div>
      )}
    </div>
  );
}

function RecoveryLine({ report }: { report: CohortReport }) {
  const [hover, setHover] = useState<number | null>(null);
  const h = 200;
  const w = 360;
  const pad = { l: 34, r: 40, t: 12, b: 24 };
  const x = (i: number) => pad.l + (i / Math.max(report.daily.length - 1, 1)) * (w - pad.l - pad.r);
  const y = (v: number) => pad.t + (1 - v) * (h - pad.t - pad.b);
  const path = report.daily.map((d, i) => `${i ? "L" : "M"}${x(i)},${y(d.recoveryRate)}`).join("");
  const last = report.daily[report.daily.length - 1]!;
  const at = hover !== null ? report.daily[hover]! : last;
  return (
    <div>
      <svg
        viewBox={`0 0 ${w} ${h}`}
        className="w-full"
        role="img"
        aria-label="Recovery rate per day"
        onMouseLeave={() => setHover(null)}
      >
        {[0, 0.5, 1].map((v) => (
          <g key={v}>
            <line x1={pad.l} x2={w - pad.r} y1={y(v)} y2={y(v)} stroke="var(--chart-grid)" />
            <text x={pad.l - 6} y={y(v) + 4} textAnchor="end" fontSize={10.5} fill="var(--muted)">
              {v * 100}%
            </text>
          </g>
        ))}
        <path
          d={`${path}L${x(report.daily.length - 1)},${y(0)}L${x(0)},${y(0)}Z`}
          fill="var(--series-1)"
          opacity={0.08}
        />
        <path
          d={path}
          fill="none"
          stroke="var(--series-1)"
          strokeWidth={2}
          strokeLinejoin="round"
          strokeLinecap="round"
        />
        {report.daily.map((d, i) => (
          <g key={d.day} onMouseEnter={() => setHover(i)}>
            <rect
              x={x(i) - 16}
              y={pad.t}
              width={32}
              height={h - pad.t - pad.b}
              fill="transparent"
            />
            <circle
              cx={x(i)}
              cy={y(d.recoveryRate)}
              r={4}
              fill="var(--series-1)"
              stroke="var(--surface)"
              strokeWidth={2}
            />
            <text x={x(i)} y={h - 6} textAnchor="middle" fontSize={11} fill="var(--muted)">
              {d.day}
            </text>
          </g>
        ))}
        <text
          x={x(report.daily.length - 1) + 8}
          y={y(last.recoveryRate) + 4}
          fontSize={12}
          fill="var(--ink)"
        >
          {percent(last.recoveryRate)}
        </text>
      </svg>
      <p className="mt-1 text-[12.5px] text-ink-2" aria-live="polite">
        Day {at.day}: {percent(at.recoveryRate)} of disengaged moments recovered · average index{" "}
        {at.avgIndex}.
      </p>
    </div>
  );
}

function HBars({ rows }: { rows: { label: string; value: number; note: string }[] }) {
  const max = Math.max(...rows.map((r) => r.value), 0.01);
  return (
    <ul className="space-y-2.5">
      {rows.map((r) => (
        <li
          key={r.label}
          className="grid grid-cols-[minmax(0,1fr)_minmax(0,1.3fr)_88px] items-center gap-3 text-[13px]"
        >
          <span className="truncate text-ink-2" title={r.label}>
            {r.label}
          </span>
          <span className="h-3 rounded-r-[4px] bg-transparent">
            <span
              className="block h-full rounded-r-[4px] bg-[var(--series-1)]"
              style={{ width: `${Math.max(2, (r.value / max) * 100)}%` }}
            />
          </span>
          <span className="tabular text-right text-ink">{r.note}</span>
        </li>
      ))}
    </ul>
  );
}

function EffectivenessGrid({ report }: { report: CohortReport }) {
  const kinds = [
    ...new Set(report.effectiveness.filter((e) => e.tries >= 3).map((e) => e.kind)),
  ] as InterventionKind[];
  const cell = (kind: InterventionKind, family: StateFamily) =>
    report.effectiveness.find((e) => e.kind === kind && e.family === family);
  return (
    <div className="overflow-x-auto">
      <table className="w-full min-w-[640px] text-[12.5px]">
        <thead>
          <tr className="text-left text-muted">
            <th className="py-2 font-normal">Intervention</th>
            {FAMILIES.map((f) => (
              <th key={f} className="py-2 font-normal">
                <span className="inline-flex items-center gap-1.5">
                  <span
                    className="inline-block size-2 rounded-full"
                    style={{ background: familyColor(f) }}
                    aria-hidden
                  />
                  {FAMILY_META[f].label}
                </span>
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {kinds.map((k) => (
            <tr key={k} className="border-t border-line">
              <td className="py-2 pr-3 text-ink">{INTERVENTION_META[k].label}</td>
              {FAMILIES.map((f) => {
                const c = cell(k, f);
                const rate = c && c.tries >= 3 ? c.recoveries / c.tries : null;
                return (
                  <td key={f} className="py-2 pr-3">
                    {rate === null ? (
                      <span className="text-muted">—</span>
                    ) : (
                      <div>
                        <span className="tabular text-ink">{percent(rate)}</span>{" "}
                        <span className="text-muted">n={c!.tries}</span>
                        <div className="mt-1 h-1.5 w-full max-w-24 rounded-full bg-surface-3">
                          <div
                            className={cn("h-full rounded-full bg-[var(--series-1)]")}
                            style={{ width: `${rate * 100}%` }}
                          />
                        </div>
                      </div>
                    )}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
