import type { ChallengeActivity, GuidedActivity, MicroActivity, QuestionActivity } from "../types";

/**
 * Practice content for one topic: Class 11 exponents and logarithms, five difficulty levels.
 * Every numeric answer here has been worked by hand; explanations show the working.
 */

export const QUESTIONS: QuestionActivity[] = [
  /* Level 1 */
  {
    id: "q-d1-a",
    type: "question",
    title: "Powers of two",
    conceptId: "doubling",
    difficulty: 1,
    prompt: "What is 2⁵?",
    options: ["10", "25", "32", "64"],
    answerIndex: 2,
    hint: "Multiply 2 by itself five times: 2, 4, 8, …",
    explanation: "2 × 2 × 2 × 2 × 2 = 32. The small 5 counts the multiplications.",
  },
  {
    id: "q-d1-b",
    type: "question",
    title: "Splitting cells",
    conceptId: "doubling",
    difficulty: 1,
    prompt: "A cell splits in two every hour. Start with 1 cell. How many after 4 hours?",
    options: ["8", "16", "5", "32"],
    answerIndex: 1,
    hint: "Hour 1: 2 cells. Hour 2: 4 cells…",
    explanation: "1 → 2 → 4 → 8 → 16. Four doublings: 2⁴ = 16.",
  },
  {
    id: "q-d1-c",
    type: "question",
    title: "Spot the pattern",
    conceptId: "doubling",
    difficulty: 1,
    prompt: "Which list is growing exponentially?",
    options: ["3, 6, 9, 12", "3, 6, 12, 24", "3, 5, 7, 9", "3, 4, 6, 9"],
    answerIndex: 1,
    hint: "Look for the same multiplier each step, not the same step size.",
    explanation: "Each term is ×2 the last: a constant multiplier, not a constant step.",
  },
  {
    id: "q-d1-d",
    type: "question",
    title: "A price rise",
    conceptId: "percent",
    difficulty: 1,
    prompt: "A ₹100 price rises by 10%. What's the new price?",
    options: ["₹101", "₹110", "₹100.10", "₹120"],
    answerIndex: 1,
    hint: "10% of 100 is 10.",
    explanation: "100 + 10% of 100 = 100 + 10 = ₹110. Same as 100 × 1.1.",
  },

  /* Level 2 */
  {
    id: "q-d2-a",
    type: "question",
    title: "Interest on interest",
    conceptId: "percent",
    difficulty: 2,
    prompt: "₹1,000 grows 10% each year. What is it worth after 2 years?",
    options: ["₹1,200", "₹1,210", "₹1,100", "₹1,020"],
    answerIndex: 1,
    hint: "Year two's 10% is taken from ₹1,100, not ₹1,000.",
    explanation: "1000 × 1.1 × 1.1 = 1,210. The extra ₹10 is interest earning interest.",
  },
  {
    id: "q-d2-b",
    type: "question",
    title: "Your first log",
    conceptId: "logs",
    difficulty: 2,
    prompt: "log₂ 64 = ?",
    options: ["5", "6", "8", "32"],
    answerIndex: 1,
    hint: "How many 2s multiply to make 64?",
    explanation: "2⁶ = 64, so log₂ 64 = 6. A log counts multiplications.",
  },
  {
    id: "q-d2-c",
    type: "question",
    title: "Tripling",
    conceptId: "doubling",
    difficulty: 2,
    prompt: "Something triples every day. Start with 1. How much after 3 days?",
    options: ["9", "27", "81", "6"],
    answerIndex: 1,
    hint: "1 → 3 → 9 → …",
    explanation: "3 × 3 × 3 = 3³ = 27.",
  },
  {
    id: "q-d2-d",
    type: "question",
    title: "The multiplier",
    conceptId: "percent",
    difficulty: 2,
    prompt: "Growing by 5% a year means multiplying by what each year?",
    options: ["0.05", "5", "1.05", "1.5"],
    answerIndex: 2,
    hint: "You keep the original 100% and add 5%.",
    explanation: "100% + 5% = 105% = × 1.05.",
  },

  /* Level 3 */
  {
    id: "q-d3-a",
    type: "question",
    title: "Rule of 70",
    conceptId: "doubling_time",
    difficulty: 3,
    prompt: "Something grows 7% per year. Roughly how long until it doubles?",
    options: ["7 years", "10 years", "14 years", "70 years"],
    answerIndex: 1,
    hint: "Doubling time ≈ 70 ÷ growth rate (%).",
    explanation: "70 ÷ 7 = 10 years. Check: 1.07¹⁰ ≈ 1.97.",
  },
  {
    id: "q-d3-b",
    type: "question",
    title: "Counting zeros",
    conceptId: "logs",
    difficulty: 3,
    prompt: "log₁₀ 1,000,000 = ?",
    options: ["5", "6", "7", "100,000"],
    answerIndex: 1,
    hint: "How many 10s multiply to make a million?",
    explanation: "10⁶ = 1,000,000, so log₁₀ 1,000,000 = 6. Base-10 logs count zeros.",
  },
  {
    id: "q-d3-c",
    type: "question",
    title: "The lily pond",
    conceptId: "doubling_time",
    difficulty: 3,
    prompt:
      "Lily pads double their area every day and cover a pond on day 30. When was the pond half covered?",
    options: ["Day 15", "Day 29", "Day 25", "Day 20"],
    answerIndex: 1,
    hint: "Go backwards one day from full.",
    explanation: "It doubles each day, so the day before it was full, it was half covered.",
  },
  {
    id: "q-d3-d",
    type: "question",
    title: "Between powers",
    conceptId: "logs",
    difficulty: 3,
    prompt: "If 2ˣ = 40, x is between…",
    options: ["4 and 5", "5 and 6", "6 and 7", "20 and 21"],
    answerIndex: 1,
    hint: "Which powers of 2 sit either side of 40?",
    explanation: "2⁵ = 32 and 2⁶ = 64, so log₂ 40 is between 5 and 6 (≈ 5.32).",
  },

  /* Level 4 */
  {
    id: "q-d4-a",
    type: "question",
    title: "A growing town",
    conceptId: "doubling_time",
    difficulty: 4,
    prompt: "A town of 5,000 grows 4% per year. About how many years until it reaches 10,000?",
    options: ["12", "18", "25", "50"],
    answerIndex: 1,
    hint: "You need 1.04ⁿ = 2. Take logs of both sides.",
    explanation: "n = ln 2 ÷ ln 1.04 ≈ 17.7, so about 18 years. The rule of 70 says 17.5.",
  },
  {
    id: "q-d4-b",
    type: "question",
    title: "Solve with logs",
    conceptId: "logs",
    difficulty: 4,
    prompt: "Solve 3ˣ = 50, to 2 decimal places.",
    options: ["2.80", "3.56", "4.17", "16.67"],
    answerIndex: 1,
    hint: "x = log 50 ÷ log 3.",
    explanation:
      "log 50 ≈ 1.699 and log 3 ≈ 0.477; 1.699 ÷ 0.477 ≈ 3.56. Check: 3³ = 27 < 50 < 81 = 3⁴.",
  },
  {
    id: "q-d4-c",
    type: "question",
    title: "Giant numbers",
    conceptId: "logs",
    difficulty: 4,
    prompt: "Which is bigger: 2¹⁰⁰ or 10³⁰?",
    options: ["2¹⁰⁰", "10³⁰", "They're equal", "Impossible to tell without a calculator"],
    answerIndex: 0,
    hint: "2¹⁰ = 1,024, which is a little more than 10³.",
    explanation: "2¹⁰⁰ = (2¹⁰)¹⁰ = 1024¹⁰ > (10³)¹⁰ = 10³⁰. It's about 1.27 × 10³⁰.",
  },
  {
    id: "q-d4-d",
    type: "question",
    title: "The credit card trap",
    conceptId: "percent",
    difficulty: 4,
    prompt: "A credit card charges 3% interest per month. What's the effective yearly rate?",
    options: ["36%", "≈ 42.6%", "≈ 39%", "3%"],
    answerIndex: 1,
    hint: "Compound it: 1.03¹².",
    explanation: "1.03¹² ≈ 1.426, so ≈ 42.6% a year: compounding adds 6.6 points to the naive 36%.",
  },

  /* Level 5 */
  {
    id: "q-d5-a",
    type: "question",
    title: "Forecasting an app",
    conceptId: "modelling",
    difficulty: 5,
    prompt:
      "An app had 2M users in January and 3.2M in July. If growth stays exponential, roughly when does it reach 10M?",
    options: [
      "December this year",
      "Around September next year",
      "About three years from January",
      "It never will",
    ],
    answerIndex: 1,
    hint: "Monthly factor = (3.2 ÷ 2)^(1/6). Then solve factorⁿ = 5.",
    explanation:
      "Monthly factor ≈ 1.6^(1/6) ≈ 1.081. Reaching ×5 from January takes n = ln 5 ÷ ln 1.081 ≈ 20.6 months: around September next year.",
  },
  {
    id: "q-d5-b",
    type: "question",
    title: "Carbon dating",
    conceptId: "modelling",
    difficulty: 5,
    prompt:
      "Carbon-14 has a half-life of 5,730 years. A bone has 30% of its original carbon-14. Roughly how old is it?",
    options: ["≈ 8,600 years", "≈ 9,950 years", "≈ 11,460 years", "≈ 17,190 years"],
    answerIndex: 1,
    hint: "Remaining = (½)^(t ÷ 5730). Solve 0.3 = (½)^(t ÷ 5730) with logs.",
    explanation:
      "t = 5730 × log₂(1 ÷ 0.3) ≈ 5730 × 1.737 ≈ 9,950 years. Sanity check: 25% would be exactly two half-lives (11,460).",
  },
  {
    id: "q-d5-c",
    type: "question",
    title: "Yearly vs monthly",
    conceptId: "percent",
    difficulty: 5,
    prompt:
      "Which grows ₹10,000 more over 10 years: 8% compounded yearly, or 7.8% compounded monthly?",
    options: ["8% yearly", "7.8% monthly", "Exactly equal", "Depends on inflation"],
    answerIndex: 1,
    hint: "Compare 1.08 with (1 + 0.078 ÷ 12)¹².",
    explanation:
      "(1.0065)¹² ≈ 1.0808 > 1.08, so monthly wins: ≈ ₹21,760 against ≈ ₹21,589 after 10 years.",
  },
  {
    id: "q-d5-d",
    type: "question",
    title: "Overtaking",
    conceptId: "modelling",
    difficulty: 5,
    prompt:
      "Your video has 50,000 views and gains 12% a day. Your friend's has 400,000 and gains 3% a day. In about how many days does yours overtake?",
    options: ["≈ 9 days", "≈ 25 days", "≈ 47 days", "Never"],
    answerIndex: 1,
    hint: "Solve (1.12 ÷ 1.03)ⁿ = 8.",
    explanation:
      "(1.12 ÷ 1.03) ≈ 1.087 per day relative growth. n = ln 8 ÷ ln 1.087 ≈ 2.079 ÷ 0.0838 ≈ 25 days.",
  },
];

export const GUIDED: GuidedActivity[] = [
  {
    id: "gs-doubling",
    type: "guided",
    title: "Doubling, one step at a time",
    conceptId: "doubling",
    difficulty: 1,
    intro: "Everything in this topic is built on one move: multiply by the same number again.",
    steps: [
      {
        prompt: "Start with 3. Double it.",
        options: ["5", "6", "9", "32"],
        answerIndex: 1,
        hint: "Doubling means × 2.",
        reveal: "3 × 2 = 6.",
      },
      {
        prompt: "Keep doubling: 6 → 12 → ?",
        options: ["18", "24", "36", "14"],
        answerIndex: 1,
        hint: "12 × 2.",
        reveal: "12 × 2 = 24.",
      },
      {
        prompt: "So 3 doubled three times is 3 × 2³. What's that?",
        options: ["9", "18", "24", "216"],
        answerIndex: 2,
        hint: "You just did it: 6, 12, …",
        reveal: "3 × 2³ = 3 × 8 = 24. The ³ counts the doublings. That's an exponent.",
      },
    ],
  },
  {
    id: "gs-percent",
    type: "guided",
    title: "Compounding in three steps",
    conceptId: "percent",
    difficulty: 2,
    intro: "₹1,000 grows 10% a year. We'll find its value after 3 years, one small step at a time.",
    steps: [
      {
        prompt: "Growing by 10% is the same as multiplying by…",
        options: ["0.1", "1.1", "10", "1.01"],
        answerIndex: 1,
        hint: "Keep the 100% you have, add 10%.",
        reveal: "100% + 10% = 110% = × 1.1.",
      },
      {
        prompt: "So after 1 year, ₹1,000 becomes…",
        options: ["₹1,010", "₹1,100", "₹1,000.10", "₹2,000"],
        answerIndex: 1,
        hint: "1000 × 1.1.",
        reveal: "₹1,100.",
      },
      {
        prompt: "After 3 years: 1000 × 1.1 × 1.1 × 1.1 = ?",
        options: ["₹1,300", "₹1,331", "₹1,210", "₹1,464"],
        answerIndex: 1,
        hint: "Year 2 is ₹1,210. Multiply by 1.1 once more.",
        reveal: "₹1,331. Not ₹1,300: each year's 10% is taken from a bigger number.",
      },
    ],
  },
  {
    id: "gs-doubling-time",
    type: "guided",
    title: "How long until it doubles?",
    conceptId: "doubling_time",
    difficulty: 3,
    intro: "A shortcut used by bankers and biologists alike: the rule of 70.",
    steps: [
      {
        prompt: "Savings grow 10% a year. The rule of 70 says doubling time ≈ 70 ÷ ?",
        options: ["10", "70", "7", "1.1"],
        answerIndex: 0,
        hint: "Divide 70 by the growth rate in percent.",
        reveal: "70 ÷ 10.",
      },
      {
        prompt: "So the savings double in about…",
        options: ["1 year", "7 years", "10 years", "70 years"],
        answerIndex: 1,
        hint: "70 ÷ 10 = ?",
        reveal: "About 7 years. (Exactly: 7.27.)",
      },
      {
        prompt: "How long until they're 4 times bigger?",
        options: ["7 years", "14 years", "21 years", "28 years"],
        answerIndex: 1,
        hint: "×4 is two doublings.",
        reveal: "Two doublings × 7 years = 14 years.",
      },
    ],
  },
  {
    id: "gs-logs",
    type: "guided",
    title: "Solving 2ˣ = 40 without a calculator",
    conceptId: "logs",
    difficulty: 2,
    intro: "Logs look scary. They're just counting. Three steps.",
    steps: [
      {
        prompt: "List powers of 2: 2, 4, 8, 16, … What's 2⁵?",
        options: ["16", "32", "64", "25"],
        answerIndex: 1,
        hint: "Five 2s multiplied.",
        reveal: "2⁵ = 32.",
      },
      {
        prompt: "40 sits between which two powers of 2?",
        options: ["16 and 32", "32 and 64", "64 and 128", "8 and 16"],
        answerIndex: 1,
        hint: "Which is just below 40, and which is just above?",
        reveal: "32 < 40 < 64, that is 2⁵ < 40 < 2⁶.",
      },
      {
        prompt: "So x = log₂ 40 is between…",
        options: ["4 and 5", "5 and 6", "6 and 7", "32 and 64"],
        answerIndex: 1,
        hint: "Count the doublings, not the numbers.",
        reveal: "Between 5 and 6 (≈ 5.32). A log counts doublings, even partial ones.",
      },
    ],
  },
];

export const MICRO_WINS: MicroActivity[] = [
  {
    id: "mw-1",
    type: "micro",
    title: "Quick one",
    conceptId: "doubling",
    prompt: "Tap the bigger one.",
    options: ["2¹⁰", "1,000"],
    answerIndex: 0,
    cheer: "2¹⁰ = 1,024. That little fact is how you compare giant numbers in your head.",
  },
  {
    id: "mw-2",
    type: "micro",
    title: "Fill the gap",
    conceptId: "doubling",
    prompt: "2, 4, 8, 16, __",
    options: ["20", "24", "32", "64"],
    answerIndex: 2,
    cheer: "32. You're doubling, and that's the whole engine behind this topic.",
  },
  {
    id: "mw-3",
    type: "micro",
    title: "Count the tens",
    conceptId: "logs",
    prompt: "10 × 10 × 10 = 10^?",
    options: ["2", "3", "10", "30"],
    answerIndex: 1,
    cheer: "10³. And counting those tens is exactly what log₁₀ does.",
  },
  {
    id: "mw-4",
    type: "micro",
    title: "Halving",
    conceptId: "doubling",
    prompt: "Half of 100, halved again, is…",
    options: ["25", "50", "20", "10"],
    answerIndex: 0,
    cheer: "25. Halving is doubling backwards: that's how half-lives work.",
  },
];

export const CHALLENGES: ChallengeActivity[] = [
  {
    id: "ch-cricket",
    type: "challenge",
    title: "The league's audience",
    conceptId: "doubling_time",
    difficulty: 3,
    frame: "cricket",
    scenario:
      "A T20 league's online audience grew from 40 million to 58 million over two seasons. The broadcaster wants to know when it passes 100 million.",
    parts: [
      {
        prompt: "Roughly what's the growth factor per season?",
        options: ["×1.10", "×1.20", "×1.45", "×1.90"],
        answerIndex: 1,
        hint: "Over two seasons it grew ×1.45. Which number, squared, is about 1.45?",
        explanation: "√1.45 ≈ 1.20. About 20% growth per season.",
      },
      {
        prompt: "At that rate, how many more seasons after 58M until it passes 100M?",
        options: ["2", "3", "5", "8"],
        answerIndex: 1,
        hint: "Multiply 58 by 1.2 until you pass 100.",
        explanation: "58 → 69.6 → 83.5 → 100.2. Three seasons.",
      },
    ],
  },
  {
    id: "ch-music",
    type: "challenge",
    title: "Your track is taking off",
    conceptId: "doubling_time",
    difficulty: 3,
    frame: "music",
    scenario: "A track you produced has 1,200 streams and is growing 15% a week.",
    parts: [
      {
        prompt: "How many streams next week?",
        options: ["1,215", "1,380", "1,500", "1,800"],
        answerIndex: 1,
        hint: "1,200 × 1.15.",
        explanation: "1,200 × 1.15 = 1,380.",
      },
      {
        prompt: "About how many weeks until it passes 10,000?",
        options: ["8", "12", "16", "30"],
        answerIndex: 2,
        hint: "Doubling time ≈ 70 ÷ 15 ≈ 4.7 weeks, and you need a bit more than 3 doublings.",
        explanation:
          "1.15ⁿ > 8.33 gives n > ln 8.33 ÷ ln 1.15 ≈ 15.2, so week 16 (≈ 11,200 streams).",
      },
    ],
  },
  {
    id: "ch-space",
    type: "challenge",
    title: "Fold your way to the Moon",
    conceptId: "logs",
    difficulty: 3,
    frame: "space",
    scenario: "A sheet of paper is 0.1 mm thick. Every fold doubles the thickness.",
    parts: [
      {
        prompt: "How thick is it after 10 folds?",
        options: ["≈ 1 mm", "≈ 10 cm", "≈ 1 m", "≈ 1 km"],
        answerIndex: 1,
        hint: "2¹⁰ ≈ 1,000.",
        explanation: "0.1 mm × 1,024 ≈ 102 mm ≈ 10 cm.",
      },
      {
        prompt: "The Moon is about 384,000 km away. About how many folds to reach it?",
        options: ["≈ 42", "≈ 420", "≈ 4,200", "≈ 1 million"],
        answerIndex: 0,
        hint: "384,000 km = 3.84 × 10¹² tenths of a millimetre. Every 10 folds multiplies by ~1,000.",
        explanation: "You need 2ⁿ ≥ 3.84 × 10¹², so n = log₂(3.84 × 10¹²) ≈ 41.8. Forty-two folds.",
      },
    ],
  },
  {
    id: "ch-startups",
    type: "challenge",
    title: "A D2C brand's revenue",
    conceptId: "percent",
    difficulty: 4,
    frame: "startups",
    scenario:
      "A direct-to-consumer brand makes ₹4 lakh a month and is growing 15% month on month. Investors want a projection.",
    parts: [
      {
        prompt: "Monthly revenue in 3 months?",
        options: ["₹5.8 lakh", "₹6.1 lakh", "₹7.2 lakh", "₹5.4 lakh"],
        answerIndex: 1,
        hint: "4 × 1.15³.",
        explanation: "1.15³ ≈ 1.521, so 4 × 1.521 ≈ ₹6.08 lakh.",
      },
      {
        prompt: "How many months until it hits ₹20 lakh a month?",
        options: ["6", "9", "12", "20"],
        answerIndex: 2,
        hint: "Solve 1.15ⁿ = 5 with logs.",
        explanation: "n = ln 5 ÷ ln 1.15 ≈ 1.609 ÷ 0.140 ≈ 11.5, so in month 12.",
      },
    ],
  },
  {
    id: "ch-gaming",
    type: "challenge",
    title: "The XP curve",
    conceptId: "logs",
    difficulty: 4,
    frame: "gaming",
    scenario:
      "In a game, the XP needed to level up multiplies by 1.25 each level. Reaching level 2 needs 100 XP.",
    parts: [
      {
        prompt: "XP needed to reach level 6?",
        options: ["≈ 200", "≈ 244", "≈ 305", "500"],
        answerIndex: 1,
        hint: "Level 6 is four steps after level 2: 100 × 1.25⁴.",
        explanation: "1.25⁴ ≈ 2.441, so ≈ 244 XP.",
      },
      {
        prompt: "What's the first level that needs more than 10,000 XP?",
        options: ["Level 12", "Level 23", "Level 42", "Level 102"],
        answerIndex: 1,
        hint: "Solve 1.25ⁿ > 100, then add 2.",
        explanation: "n > ln 100 ÷ ln 1.25 ≈ 20.6, so n = 21 steps after level 2: level 23.",
      },
    ],
  },
  {
    id: "ch-cricket-valuation",
    type: "challenge",
    title: "A franchise's valuation",
    conceptId: "modelling",
    difficulty: 5,
    frame: "cricket",
    scenario:
      "A cricket franchise was valued at ₹1,500 crore. Eight years later it's ₹6,000 crore.",
    parts: [
      {
        prompt: "What's the average yearly growth rate?",
        options: ["≈ 12.5%", "≈ 19%", "≈ 37.5%", "≈ 50%"],
        answerIndex: 1,
        hint: "It grew ×4 in 8 years. Yearly factor = 4^(1/8).",
        explanation:
          "4^(1/8) = 2^(1/4) ≈ 1.189: about 19% a year, not 37.5% (that's 300% ÷ 8, ignoring compounding).",
      },
      {
        prompt: "Using that rate, how long does each doubling take?",
        options: ["≈ 2 years", "≈ 4 years", "≈ 6 years", "≈ 8 years"],
        answerIndex: 1,
        hint: "×4 is two doublings. Or use the rule of 70.",
        explanation:
          "Two doublings in 8 years means 4 years each. The rule of 70 agrees: 70 ÷ 19 ≈ 3.7.",
      },
    ],
  },
  {
    id: "ch-startups-overtake",
    type: "challenge",
    title: "The challenger brand",
    conceptId: "modelling",
    difficulty: 5,
    frame: "startups",
    scenario:
      "Startup A has 1 million users, growing 5% a month. Startup B has 200,000, growing 15% a month.",
    parts: [
      {
        prompt: "How many users does A have after 12 months?",
        options: ["≈ 1.6M", "≈ 1.8M", "≈ 2.2M", "≈ 1.05M"],
        answerIndex: 1,
        hint: "1.05¹².",
        explanation: "1.05¹² ≈ 1.796, so ≈ 1.8 million.",
      },
      {
        prompt: "In about which month does B overtake A?",
        options: ["≈ 8", "≈ 18", "≈ 36", "Never"],
        answerIndex: 1,
        hint: "Solve 200,000 × 1.15ⁿ = 1,000,000 × 1.05ⁿ, that is (1.15 ÷ 1.05)ⁿ = 5.",
        explanation: "n = ln 5 ÷ ln(1.0952) ≈ 1.609 ÷ 0.091 ≈ 17.7: around month 18.",
      },
    ],
  },
];
