-- Generated from the engine's content library by src/lib/activity-catalog.ts. Do not edit by
-- hand: change the content, then regenerate (see apps/attune/README.md).
insert into public.activities (id, type, concept_id, difficulty, title) values
  ('q-d1-a', 'question', 'doubling', 1, 'Powers of two'),
  ('q-d1-b', 'question', 'doubling', 1, 'Splitting cells'),
  ('q-d1-c', 'question', 'doubling', 1, 'Spot the pattern'),
  ('q-d1-d', 'question', 'percent', 1, 'A price rise'),
  ('q-d2-a', 'question', 'percent', 2, 'Interest on interest'),
  ('q-d2-b', 'question', 'logs', 2, 'Your first log'),
  ('q-d2-c', 'question', 'doubling', 2, 'Tripling'),
  ('q-d2-d', 'question', 'percent', 2, 'The multiplier'),
  ('q-d3-a', 'question', 'doubling_time', 3, 'Rule of 70'),
  ('q-d3-b', 'question', 'logs', 3, 'Counting zeros'),
  ('q-d3-c', 'question', 'doubling_time', 3, 'The lily pond'),
  ('q-d3-d', 'question', 'logs', 3, 'Between powers'),
  ('q-d4-a', 'question', 'doubling_time', 4, 'A growing town'),
  ('q-d4-b', 'question', 'logs', 4, 'Solve with logs'),
  ('q-d4-c', 'question', 'logs', 4, 'Giant numbers'),
  ('q-d4-d', 'question', 'percent', 4, 'The credit card trap'),
  ('q-d5-a', 'question', 'modelling', 5, 'Forecasting an app'),
  ('q-d5-b', 'question', 'modelling', 5, 'Carbon dating'),
  ('q-d5-c', 'question', 'percent', 5, 'Yearly vs monthly'),
  ('q-d5-d', 'question', 'modelling', 5, 'Overtaking'),
  ('gs-doubling', 'guided', 'doubling', 1, 'Doubling, one step at a time'),
  ('gs-percent', 'guided', 'percent', 2, 'Compounding in three steps'),
  ('gs-doubling-time', 'guided', 'doubling_time', 3, 'How long until it doubles?'),
  ('gs-logs', 'guided', 'logs', 2, 'Solving 2ˣ = 40 without a calculator'),
  ('mw-1', 'micro', 'doubling', 1, 'Quick one'),
  ('mw-2', 'micro', 'doubling', 1, 'Fill the gap'),
  ('mw-3', 'micro', 'logs', 1, 'Count the tens'),
  ('mw-4', 'micro', 'doubling', 1, 'Halving'),
  ('ch-cricket', 'challenge', 'doubling_time', 3, 'The league''s audience'),
  ('ch-music', 'challenge', 'doubling_time', 3, 'Your track is taking off'),
  ('ch-space', 'challenge', 'logs', 3, 'Fold your way to the Moon'),
  ('ch-startups', 'challenge', 'percent', 4, 'A D2C brand''s revenue'),
  ('ch-gaming', 'challenge', 'logs', 4, 'The XP curve'),
  ('ch-cricket-valuation', 'challenge', 'modelling', 5, 'A franchise''s valuation'),
  ('ch-startups-overtake', 'challenge', 'modelling', 5, 'The challenger brand'),
  ('ex-logs-text', 'explanation', 'logs', null, 'What a logarithm counts'),
  ('ex-logs-visual', 'explanation', 'logs', null, 'The doubling ladder'),
  ('ex-logs-analogy', 'explanation', 'logs', null, 'Logs are folding paper'),
  ('ex-logs-worked', 'explanation', 'logs', null, 'Solving an exponential equation'),
  ('ex-logs-dialogue', 'explanation', 'logs', null, 'Logs in a minute'),
  ('ex-percent-text', 'explanation', 'percent', null, 'Growing by a percentage means multiplying'),
  ('ex-percent-visual', 'explanation', 'percent', null, 'Simple vs compound, year by year'),
  ('ex-percent-analogy', 'explanation', 'percent', null, 'The snowball'),
  ('ex-percent-worked', 'explanation', 'percent', null, 'Compounding, worked'),
  ('ex-doubling-text', 'explanation', 'doubling', null, 'Exponential means repeated multiplication'),
  ('ex-doubling-visual', 'explanation', 'doubling', null, 'Adding vs multiplying'),
  ('ex-doubling-analogy', 'explanation', 'doubling', null, 'How a secret spreads'),
  ('ex-doubling-time-text', 'explanation', 'doubling_time', null, 'The rule of 70'),
  ('ex-doubling-time-analogy', 'explanation', 'doubling_time', null, 'The lily pond'),
  ('ex-doubling-time-worked', 'explanation', 'doubling_time', null, 'Counting doublings'),
  ('ex-modelling-text', 'explanation', 'modelling', null, 'Two points make a forecast'),
  ('ex-modelling-worked', 'explanation', 'modelling', null, 'Forecasting an app''s users'),
  ('cp-paper-moon', 'curiosity', 'logs', null, 'Folding paper to the Moon'),
  ('cp-loudness', 'curiosity', 'logs', null, 'Why loudness is logarithmic'),
  ('mission-viral', 'mission', 'percent', 3, 'Mission: will the club page hit 2,000?'),
  ('mission-offer', 'mission', 'percent', 4, 'Mission: pick the better offer'),
  ('rf-logs', 'reflection', 'logs', null, 'Lock it in'),
  ('rf-percent', 'reflection', 'percent', null, 'Lock it in'),
  ('rf-general', 'reflection', 'doubling', null, 'Lock it in'),
  ('br-reset', 'break', 'doubling', null, 'Two-minute reset'),
  ('br-stop', 'break', 'doubling', null, 'This is a good place to stop')
on conflict (id) do update set
  type = excluded.type,
  concept_id = excluded.concept_id,
  difficulty = excluded.difficulty,
  title = excluded.title;
