import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { AwsClient } from "aws4fetch";
import type { Config } from "../config";

/**
 * Where optimized images live. The app only ever talks to this interface, so swapping the
 * provider (Cloudflare R2, Supabase Storage, AWS S3, MinIO…) is configuration, not code.
 */
export interface MediaStorage {
  readonly driver: "local" | "s3";
  /** Stores one object and returns the URL browsers load it from. */
  put(key: string, body: Buffer, contentType: string): Promise<string>;
  remove(keys: string[]): Promise<void>;
}

/** Keys are generated by the server only (`media/<owner>/<asset>-<size>.webp`). */
export const STORAGE_KEY_PATTERN = /^media\/[a-z0-9]{6,40}\/[a-z0-9]{6,40}(?:-\d{2,4})?\.webp$/;

const IMMUTABLE = "public, max-age=31536000, immutable";

/**
 * Development storage: files on the server's disk, served by the API under
 * /api/media/files/… (same origin as the app through the /api proxy). Not for production
 * on hosts with an ephemeral disk (Render, Railway, Fly): files vanish on every deploy.
 */
export class LocalStorage implements MediaStorage {
  readonly driver = "local" as const;
  constructor(readonly dir: string) {}

  filePath(key: string) {
    if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
    return path.join(this.dir, key);
  }

  async put(key: string, body: Buffer) {
    const file = this.filePath(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
    return `/api/media/files/${key}`;
  }

  async remove(keys: string[]) {
    await Promise.all(keys.map((k) => rm(this.filePath(k), { force: true })));
  }
}

/** Any S3-compatible bucket, signed with SigV4 (aws4fetch: no AWS SDK needed). */
export class S3Storage implements MediaStorage {
  readonly driver = "s3" as const;
  private client: AwsClient;

  constructor(
    private opts: {
      endpoint: string;
      region: string;
      bucket: string;
      accessKeyId: string;
      secretAccessKey: string;
      publicUrl: string;
    },
    private fetchImpl: typeof fetch = fetch,
  ) {
    this.client = new AwsClient({
      accessKeyId: opts.accessKeyId,
      secretAccessKey: opts.secretAccessKey,
      service: "s3",
      region: opts.region,
    });
  }

  private objectUrl(key: string) {
    // Path-style addressing works on R2, Supabase, MinIO and AWS alike.
    return `${this.opts.endpoint.replace(/\/$/, "")}/${encodeURIComponent(this.opts.bucket)}/${key}`;
  }

  async put(key: string, body: Buffer, contentType: string) {
    if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
    const signed = await this.client.sign(this.objectUrl(key), {
      method: "PUT",
      body: new Uint8Array(body),
      headers: { "content-type": contentType, "cache-control": IMMUTABLE },
    });
    const res = await this.fetchImpl(signed);
    if (!res.ok) {
      throw new Error(`Object storage rejected the upload (${res.status})`);
    }
    return `${this.opts.publicUrl.replace(/\/$/, "")}/${key}`;
  }

  async remove(keys: string[]) {
    await Promise.all(
      keys.map(async (key) => {
        if (!STORAGE_KEY_PATTERN.test(key)) return;
        const signed = await this.client.sign(this.objectUrl(key), { method: "DELETE" });
        const res = await this.fetchImpl(signed);
        if (!res.ok && res.status !== 404) {
          throw new Error(`Object storage refused the delete (${res.status})`);
        }
      }),
    );
  }
}

export interface StorageChoice {
  storage: MediaStorage | null;
  /** Shown to organisers when uploads are off. */
  reason: string | null;
}

/** Picks the storage from the environment. Production never silently falls back to disk. */
export function createStorage(config: Config): StorageChoice {
  const wanted =
    config.MEDIA_STORAGE ?? (config.S3_BUCKET ? "s3" : config.isProd ? "none" : "local");
  if (wanted === "none") {
    return {
      storage: null,
      reason:
        "Image uploads need object storage. Set the S3_* variables on the game server (Cloudflare R2, Supabase Storage or AWS S3) — see the README.",
    };
  }
  if (wanted === "local") {
    return { storage: new LocalStorage(path.resolve(config.MEDIA_LOCAL_DIR)), reason: null };
  }
  const missing = (
    [
      "S3_ENDPOINT",
      "S3_BUCKET",
      "S3_ACCESS_KEY_ID",
      "S3_SECRET_ACCESS_KEY",
      "S3_PUBLIC_URL",
    ] as const
  ).filter((k) => !config[k]);
  if (missing.length) {
    return {
      storage: null,
      reason: `Image uploads are misconfigured: ${missing.join(", ")} ${missing.length === 1 ? "is" : "are"} missing on the game server.`,
    };
  }
  return {
    storage: new S3Storage({
      endpoint: config.S3_ENDPOINT!,
      region: config.S3_REGION,
      bucket: config.S3_BUCKET!,
      accessKeyId: config.S3_ACCESS_KEY_ID!,
      secretAccessKey: config.S3_SECRET_ACCESS_KEY!,
      publicUrl: config.S3_PUBLIC_URL!,
    }),
    reason: null,
  };
}
