import { createWriteStream } from "node:fs";
import { mkdir, open, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { AwsClient } from "aws4fetch";
import type { Config } from "../config";

/**
 * Where optimized images live. The app only ever talks to this interface, so swapping the
 * provider (Cloudflare R2, Supabase Storage, AWS S3, MinIO…) is configuration, not code.
 */
export interface MediaStorage {
  readonly driver: "local" | "s3";
  /** Stores one object and returns the URL browsers load it from. */
  put(key: string, body: Buffer, contentType: string): Promise<string>;
  remove(keys: string[]): Promise<void>;
  /** The URL browsers load an object from. */
  publicUrl(key: string): string;
  /**
   * Where a browser may upload a large file directly (a presigned bucket URL), or null when
   * it must go through the game server instead (local storage).
   */
  directUpload(
    key: string,
    contentType: string,
  ): Promise<{ url: string; headers: Record<string, string> } | null>;
  /** Size of a stored object, or null if it isn't there. */
  size(key: string): Promise<number | null>;
  /** The first `n` bytes of an object, to check what it really is. */
  head(key: string, n: number): Promise<Buffer>;
}

/**
 * Keys are generated by the server only: `media/<owner>/<asset>-<size>.webp` for images
 * and posters, `media/<owner>/<asset>.mp4|webm` for videos.
 */
export const STORAGE_KEY_PATTERN =
  /^media\/[a-z0-9]{6,40}\/[a-z0-9]{6,40}(?:(?:-\d{2,4})?\.webp|\.mp4|\.webm)$/;

export const contentTypeFor = (key: string) =>
  key.endsWith(".mp4") ? "video/mp4" : key.endsWith(".webm") ? "video/webm" : "image/webp";

/** Thrown by a streamed upload that goes past its size limit. */
export class TooLargeError extends Error {}

const IMMUTABLE = "public, max-age=31536000, immutable";

/**
 * Development storage: files on the server's disk, served by the API under
 * /api/media/files/… (same origin as the app through the /api proxy). Not for production
 * on hosts with an ephemeral disk (Render, Railway, Fly): files vanish on every deploy.
 */
export class LocalStorage implements MediaStorage {
  readonly driver = "local" as const;
  constructor(readonly dir: string) {}

  filePath(key: string) {
    if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
    return path.join(this.dir, key);
  }

  publicUrl(key: string) {
    return `/api/media/files/${key}`;
  }

  async put(key: string, body: Buffer) {
    const file = this.filePath(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
    return this.publicUrl(key);
  }

  /** Streams a request body to disk, stopping (and cleaning up) past `maxBytes`. */
  async write(key: string, body: Readable, maxBytes: number): Promise<number> {
    const file = this.filePath(key);
    await mkdir(path.dirname(file), { recursive: true });
    let bytes = 0;
    try {
      await pipeline(
        body,
        async function* (source) {
          for await (const chunk of source as AsyncIterable<Buffer>) {
            bytes += chunk.length;
            if (bytes > maxBytes) throw new TooLargeError();
            yield chunk;
          }
        },
        createWriteStream(file),
      );
    } catch (err) {
      await rm(file, { force: true });
      throw err;
    }
    return bytes;
  }

  async directUpload() {
    return null;
  }

  async size(key: string) {
    const info = await stat(this.filePath(key)).catch(() => null);
    return info?.isFile() ? info.size : null;
  }

  async head(key: string, n: number) {
    const fh = await open(this.filePath(key), "r");
    try {
      const buf = Buffer.alloc(n);
      const { bytesRead } = await fh.read(buf, 0, n, 0);
      return buf.subarray(0, bytesRead);
    } finally {
      await fh.close();
    }
  }

  async remove(keys: string[]) {
    await Promise.all(keys.map((k) => rm(this.filePath(k), { force: true })));
  }
}

/** Any S3-compatible bucket, signed with SigV4 (aws4fetch: no AWS SDK needed). */
export class S3Storage implements MediaStorage {
  readonly driver = "s3" as const;
  private client: AwsClient;

  constructor(
    private opts: {
      endpoint: string;
      region: string;
      bucket: string;
      accessKeyId: string;
      secretAccessKey: string;
      publicUrl: string;
    },
    private fetchImpl: typeof fetch = fetch,
  ) {
    this.client = new AwsClient({
      accessKeyId: opts.accessKeyId,
      secretAccessKey: opts.secretAccessKey,
      service: "s3",
      region: opts.region,
    });
  }

  private objectUrl(key: string) {
    // Path-style addressing works on R2, Supabase, MinIO and AWS alike.
    return `${this.opts.endpoint.replace(/\/$/, "")}/${encodeURIComponent(this.opts.bucket)}/${key}`;
  }

  publicUrl(key: string) {
    return `${this.opts.publicUrl.replace(/\/$/, "")}/${key}`;
  }

  /**
   * A presigned PUT, valid for 15 minutes, so the browser sends the video straight to the
   * bucket: the game server never holds it. Needs a CORS rule on the bucket (see README).
   */
  async directUpload(key: string, contentType: string) {
    if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
    const url = new URL(this.objectUrl(key));
    url.searchParams.set("X-Amz-Expires", "900");
    const signed = await this.client.sign(url.toString(), {
      method: "PUT",
      headers: { "content-type": contentType },
      // Sign the content type too (aws4fetch skips it by default), so the bucket can't be
      // made to serve the upload as anything but the video type checked here.
      aws: { signQuery: true, allHeaders: true },
    });
    return { url: signed.url, headers: { "content-type": contentType } };
  }

  async size(key: string) {
    if (!STORAGE_KEY_PATTERN.test(key)) return null;
    const res = await this.fetchImpl(
      await this.client.sign(this.objectUrl(key), { method: "HEAD" }),
    );
    if (res.status === 404) return null;
    if (!res.ok) throw new Error(`Object storage refused the lookup (${res.status})`);
    return Number(res.headers.get("content-length") ?? 0);
  }

  async head(key: string, n: number) {
    if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
    const res = await this.fetchImpl(
      await this.client.sign(this.objectUrl(key), {
        method: "GET",
        headers: { range: `bytes=0-${n - 1}` },
      }),
    );
    if (!res.ok) throw new Error(`Object storage refused the read (${res.status})`);
    return Buffer.from(await res.arrayBuffer()).subarray(0, n);
  }

  async put(key: string, body: Buffer, contentType: string) {
    if (!STORAGE_KEY_PATTERN.test(key)) throw new Error("Invalid storage key");
    const signed = await this.client.sign(this.objectUrl(key), {
      method: "PUT",
      body: new Uint8Array(body),
      headers: { "content-type": contentType, "cache-control": IMMUTABLE },
    });
    const res = await this.fetchImpl(signed);
    if (!res.ok) {
      throw new Error(`Object storage rejected the upload (${res.status})`);
    }
    return this.publicUrl(key);
  }

  async remove(keys: string[]) {
    await Promise.all(
      keys.map(async (key) => {
        if (!STORAGE_KEY_PATTERN.test(key)) return;
        const signed = await this.client.sign(this.objectUrl(key), { method: "DELETE" });
        const res = await this.fetchImpl(signed);
        if (!res.ok && res.status !== 404) {
          throw new Error(`Object storage refused the delete (${res.status})`);
        }
      }),
    );
  }
}

export interface StorageChoice {
  storage: MediaStorage | null;
  /** Shown to organisers when uploads are off. */
  reason: string | null;
}

/** Picks the storage from the environment. Production never silently falls back to disk. */
export function createStorage(config: Config): StorageChoice {
  const wanted =
    config.MEDIA_STORAGE ?? (config.S3_BUCKET ? "s3" : config.isProd ? "none" : "local");
  if (wanted === "none") {
    return {
      storage: null,
      reason:
        "Image uploads need object storage. Set the S3_* variables on the game server (Cloudflare R2, Supabase Storage or AWS S3) — see the README.",
    };
  }
  if (wanted === "local") {
    return { storage: new LocalStorage(path.resolve(config.MEDIA_LOCAL_DIR)), reason: null };
  }
  const missing = (
    [
      "S3_ENDPOINT",
      "S3_BUCKET",
      "S3_ACCESS_KEY_ID",
      "S3_SECRET_ACCESS_KEY",
      "S3_PUBLIC_URL",
    ] as const
  ).filter((k) => !config[k]);
  if (missing.length) {
    return {
      storage: null,
      reason: `Image uploads are misconfigured: ${missing.join(", ")} ${missing.length === 1 ? "is" : "are"} missing on the game server.`,
    };
  }
  return {
    storage: new S3Storage({
      endpoint: config.S3_ENDPOINT!,
      region: config.S3_REGION,
      bucket: config.S3_BUCKET!,
      accessKeyId: config.S3_ACCESS_KEY_ID!,
      secretAccessKey: config.S3_SECRET_ACCESS_KEY!,
      publicUrl: config.S3_PUBLIC_URL!,
    }),
    reason: null,
  };
}
